name: 'GitHub Actions Weather Bot'

on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./report.sh
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Weather Report (${{env.REPORT_DATE}})
          body: file://report.html
          to: 464218207@qq.com,flatred@163.com
          from: GitHub Actions
          content_type: text/html
